### Homework 3 Numpy Arrays

1. Open `cars.csv` in jupyter and look at the data. (Double click `cars.csv` to open in a new tab).
2. We are converting each **column** into an numpy array.
3. Notice we have text, integer and float data. 
4. Take care not to overwrite your starter code.

In [1]:
#Starter code. Do NOT modify this cell
import pandas as pd
import numpy as np

# Read in dataset
df = pd.read_csv('cars.csv',delimiter=';')

# Convert each column to an np.array
car = df.Car.to_numpy()
mpg = df.MPG.to_numpy()
cylinders = df.Cylinders.to_numpy()
displacement = df.Displacement.to_numpy()
horsepower = df.Horsepower.to_numpy()
weight = df.Weight.to_numpy()
acceleration = df.Acceleration.to_numpy()
model = df.Model.to_numpy()
origin = df.Origin.to_numpy()

# create an array of headers
headers = np.array(['Car', 'MPG', 'Cylinders', 'Displacement', 'Horsepower', 'Weight','Acceleration', 'Model', 'Origin'])


In [50]:
#Starter code. Do NOT modify this cell
import pandas as pd
import numpy as np

# Read in dataset
df = pd.read_csv('cars.csv',delimiter=';')

# Convert each column to an np.array
car = df.Car.to_numpy()
mpg = df.MPG.to_numpy()
cylinders = df.Cylinders.to_numpy()
displacement = df.Displacement.to_numpy()
horsepower = df.Horsepower.to_numpy()
weight = df.Weight.to_numpy()
acceleration = df.Acceleration.to_numpy()
model = df.Model.to_numpy()
origin = df.Origin.to_numpy()

# create an array of headers
headers = np.array(['Car', 'MPG', 'Cylinders', 'Displacement', 'Horsepower', 'Weight','Acceleration', 'Model', 'Origin'])

X = np.array(df.iloc[0:406, 0:9])
print(headers)
print(X)

['Car' 'MPG' 'Cylinders' 'Displacement' 'Horsepower' 'Weight'
 'Acceleration' 'Model' 'Origin']
[['Chevrolet Chevelle Malibu' 18.0 8 ... 12.0 70 'US']
 ['Buick Skylark 320' 15.0 8 ... 11.5 70 'US']
 ['Plymouth Satellite' 18.0 8 ... 11.0 70 'US']
 ...
 ['Dodge Rampage' 32.0 4 ... 11.6 82 'US']
 ['Ford Ranger' 28.0 4 ... 18.6 82 'US']
 ['Chevy S-10' 31.0 4 ... 19.4 82 'US']]


In [176]:
import pandas as pd
import numpy as np

# Read in dataset
df = pd.read_csv('cars.csv',delimiter=';')

# Convert each column to an np.array
car = df.Car.to_numpy()
CR = np.array(car)
print(CR)

mpg = df.MPG.to_numpy()
empg = np.array(mpg)
print(empg) 

cylinders = df.Cylinders.to_numpy()
clnder = np.array(cylinders)
print(clnder)

displacement = df.Displacement.to_numpy()
displace = np.array(displacement)
print(displace)

horsepower = df.Horsepower.to_numpy()
HP = np.array(horsepower)
print(HP)

weight = df.Weight.to_numpy()
weyt = np.array(weight)
print(weyt)

acceleration = df.Acceleration.to_numpy()
acc = np.array(acceleration)
print(acc)

model = df.Model.to_numpy()
mdl = np.array(model)
print(mdl)

origin = df.Origin.to_numpy()
org = np.array(origin)
print(org)

# create an array of headers
headers = np.array(['Car', 'MPG', 'Cylinders', 'Displacement', 'Horsepower', 'Weight','Acceleration', 'Model', 'Origin'])
print(headers)

['Chevrolet Chevelle Malibu' 'Buick Skylark 320' 'Plymouth Satellite'
 'AMC Rebel SST' 'Ford Torino' 'Ford Galaxie 500' 'Chevrolet Impala'
 'Plymouth Fury iii' 'Pontiac Catalina' 'AMC Ambassador DPL'
 'Citroen DS-21 Pallas' 'Chevrolet Chevelle Concours (sw)'
 'Ford Torino (sw)' 'Plymouth Satellite (sw)' 'AMC Rebel SST (sw)'
 'Dodge Challenger SE' "Plymouth 'Cuda 340" 'Ford Mustang Boss 302'
 'Chevrolet Monte Carlo' 'Buick Estate Wagon (sw)'
 'Toyota Corolla Mark ii' 'Plymouth Duster' 'AMC Hornet' 'Ford Maverick'
 'Datsun PL510' 'Volkswagen 1131 Deluxe Sedan' 'Peugeot 504' 'Audi 100 LS'
 'Saab 99e' 'BMW 2002' 'AMC Gremlin' 'Ford F250' 'Chevy C20' 'Dodge D200'
 'Hi 1200D' 'Datsun PL510' 'Chevrolet Vega 2300' 'Toyota Corolla'
 'Ford Pinto' 'Volkswagen Super Beetle 117' 'AMC Gremlin'
 'Plymouth Satellite Custom' 'Chevrolet Chevelle Malibu' 'Ford Torino 500'
 'AMC Matador' 'Chevrolet Impala' 'Pontiac Catalina Brougham'
 'Ford Galaxie 500' 'Plymouth Fury iii' 'Dodge Monaco (sw)'
 'Ford Count

1. How can you get help on `np.array`?

Call dir() on np.array.

Call dir() on car.

Note the difference. `car` has methods and attributes we can use.

In [24]:
#lookfor()--> does a keyword search on docstrings. With this function, you can go through 
#all of the search results. But if you specify what you are seeking help for, you can narrow the results

#info()--> gives brief information and examples of functions, classes, or modules

#dir()--> returns the attributes and methods of functions or other objects in the form of a list

dir(np.array)

['__call__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__name__',
 '__ne__',
 '__new__',
 '__qualname__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__self__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__text_signature__']

In [25]:
dir(car)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

 2.What are the numpy datatypes for the `car`,`mpg`, `horsepower` and `origin` arrays? (Hint: Not `type(car)` and use `print()` to print the numpy type.)

In [181]:
print("calling on array?")
print(CR.dtype)
print(empg.dtype)
print(HP.dtype)
print(org.dtype)

print("calling on column?")
print(car.dtype)
print(mpg.dtype)
print(horsepower.dtype)
print(origin.dtype)

calling on array?
object
float64
float64
object
calling on column?
object
float64
float64
object


3.`numpy` is often imported as `np`. What is this action called? Why might you do this? 

In [ ]:
#Importing numpy as np is like giving it a nickname or alias.
#We do this so that we can write shorter lines. We would call on np instead of numpy. 

4.Each of the arrays (cars, mpg, cylinders, etc..) has how many dimensions? Show how to find this using code. 

In [182]:
print(CR.ndim)
print(empg.ndim)
print(clnder.ndim)
print(displace.ndim)
print(HP.ndim)
print(weyt.ndim)
print(acc.ndim)
print(mdl.ndim)
print(org.ndim) 

1
1
1
1
1
1
1
1
1


5.Show how to:

- multiply the `mpg` array by 12.
- divide the `mpg` array by 3.
- raise the `mpg` array to the power of 4.
- take the square root of the `mpg` array.

In [184]:
n = 12
np.multiply(empg,n)

array([216. , 180. , 216. , 192. , 204. , 180. , 168. , 168. , 168. ,
       180. ,   0. ,   0. ,   0. ,   0. ,   0. , 180. , 168. ,   0. ,
       180. , 168. , 288. , 264. , 216. , 252. , 324. , 312. , 300. ,
       288. , 300. , 312. , 252. , 120. , 120. , 132. , 108. , 324. ,
       336. , 300. , 300. ,   0. , 228. , 192. , 204. , 228. , 216. ,
       168. , 168. , 168. , 168. , 144. , 156. , 156. , 216. , 264. ,
       228. , 216. , 276. , 336. , 360. , 360. , 372. , 420. , 324. ,
       312. , 288. , 300. , 276. , 240. , 252. , 156. , 168. , 180. ,
       168. , 204. , 132. , 156. , 144. , 156. , 228. , 180. , 156. ,
       156. , 168. , 216. , 264. , 252. , 312. , 264. , 336. , 276. ,
       336. , 324. , 156. , 168. , 156. , 168. , 180. , 144. , 156. ,
       156. , 168. , 156. , 144. , 156. , 216. , 192. , 216. , 216. ,
       276. , 312. , 132. , 144. , 156. , 144. , 216. , 240. , 252. ,
       264. , 216. , 228. , 252. , 312. , 180. , 192. , 348. , 288. ,
       240. , 228. ,

In [185]:
n2 = 3
np.divide(empg,n2)

array([ 6.        ,  5.        ,  6.        ,  5.33333333,  5.66666667,
        5.        ,  4.66666667,  4.66666667,  4.66666667,  5.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        5.        ,  4.66666667,  0.        ,  5.        ,  4.66666667,
        8.        ,  7.33333333,  6.        ,  7.        ,  9.        ,
        8.66666667,  8.33333333,  8.        ,  8.33333333,  8.66666667,
        7.        ,  3.33333333,  3.33333333,  3.66666667,  3.        ,
        9.        ,  9.33333333,  8.33333333,  8.33333333,  0.        ,
        6.33333333,  5.33333333,  5.66666667,  6.33333333,  6.        ,
        4.66666667,  4.66666667,  4.66666667,  4.66666667,  4.        ,
        4.33333333,  4.33333333,  6.        ,  7.33333333,  6.33333333,
        6.        ,  7.66666667,  9.33333333, 10.        , 10.        ,
       10.33333333, 11.66666667,  9.        ,  8.66666667,  8.        ,
        8.33333333,  7.66666667,  6.66666667,  7.        ,  4.33

In [188]:
#raise the mpg array to the power of 4.
n3 = 4
np.power(empg,4)

array([ 104976.    ,   50625.    ,  104976.    ,   65536.    ,
         83521.    ,   50625.    ,   38416.    ,   38416.    ,
         38416.    ,   50625.    ,       0.    ,       0.    ,
             0.    ,       0.    ,       0.    ,   50625.    ,
         38416.    ,       0.    ,   50625.    ,   38416.    ,
        331776.    ,  234256.    ,  104976.    ,  194481.    ,
        531441.    ,  456976.    ,  390625.    ,  331776.    ,
        390625.    ,  456976.    ,  194481.    ,   10000.    ,
         10000.    ,   14641.    ,    6561.    ,  531441.    ,
        614656.    ,  390625.    ,  390625.    ,       0.    ,
        130321.    ,   65536.    ,   83521.    ,  130321.    ,
        104976.    ,   38416.    ,   38416.    ,   38416.    ,
         38416.    ,   20736.    ,   28561.    ,   28561.    ,
        104976.    ,  234256.    ,  130321.    ,  104976.    ,
        279841.    ,  614656.    ,  810000.    ,  810000.    ,
        923521.    , 1500625.    ,  531441.    ,  45697

In [189]:
#take the square root of the mpg array.

square = np.sqrt(empg)

print(square)

[4.24264069 3.87298335 4.24264069 4.         4.12310563 3.87298335
 3.74165739 3.74165739 3.74165739 3.87298335 0.         0.
 0.         0.         0.         3.87298335 3.74165739 0.
 3.87298335 3.74165739 4.89897949 4.69041576 4.24264069 4.58257569
 5.19615242 5.09901951 5.         4.89897949 5.         5.09901951
 4.58257569 3.16227766 3.16227766 3.31662479 3.         5.19615242
 5.29150262 5.         5.         0.         4.35889894 4.
 4.12310563 4.35889894 4.24264069 3.74165739 3.74165739 3.74165739
 3.74165739 3.46410162 3.60555128 3.60555128 4.24264069 4.69041576
 4.35889894 4.24264069 4.79583152 5.29150262 5.47722558 5.47722558
 5.56776436 5.91607978 5.19615242 5.09901951 4.89897949 5.
 4.79583152 4.47213595 4.58257569 3.60555128 3.74165739 3.87298335
 3.74165739 4.12310563 3.31662479 3.60555128 3.46410162 3.60555128
 4.35889894 3.87298335 3.60555128 3.60555128 3.74165739 4.24264069
 4.69041576 4.58257569 5.09901951 4.69041576 5.29150262 4.79583152
 5.29150262 5.19615242 3.60

6.What is the ___ of `horsepower`?
- sum
- min
- max
- median
- Optional: mode (May need to google help)

In [191]:
#sum of horsepower

hp_sum = sum(HP)
print ('Sum of the array is ',hp_sum)

a = len(HP)

#min of horsepower
def Min(HP, a):
    A = HP[0]
    for i in range(1,a):
        A = min(A, HP[i])
    return A
print ("Minimum:", Min(HP, a))

# Max of horsepower
def Max(HP, a):
    B = HP[0]
    for i in range(1,a):
        B = max(B, HP[i])
    return B
print ("Max:", Max(HP, a))

#Median of horsepower
C = np.median(HP)
print("Median:", C)

Sum of the array is  42033.0
Minimum: 0.0
Max: 230.0
Median: 93.5


7.Select a subset of `acceleration`. 

- Select only the first 5 elements.
- Select every other element (new selection).

In [194]:
print(acc[0:5])

print(acc[::2])

[12.  11.5 11.  12.  10.5]
[12.  11.  10.5  9.  10.  17.5 11.  11.   8.   9.5 15.  15.5 14.5 17.5
 17.5 15.  15.  18.5 15.5 19.  13.  15.5 15.5 11.5 13.  12.  13.5 15.
 14.  19.5 19.  19.  15.5 23.5 16.5 12.  13.  11.  13.5 13.5 14.  14.
 18.  18.  17.  15.  13.  13.  12.5 12.  14.5 11.  16.5 16.  16.  14.
 13.  15.  19.5 13.5 14.  13.  19.5 14.  11.  13.5 16.5 16.  19.  21.
 17.  16.5 14.5 16.  16.5 14.5 19.  15.5 15.  16.  16.  19.5 14.  13.5
 18.5 19.  13.5 16.  16.  13.5 17.  14.  15.  14.5 17.5 16.9 17.7 13.
 13.9 15.4 17.6 22.2 14.2 17.7 16.2 12.2 16.4 15.7 21.9 16.7 12.  14.
 14.8 15.5 12.5 13.7 16.4 17.7 11.1 12.2 14.5 18.2 17.  16.4 14.5 13.5
 14.4 18.6 15.5 12.8 18.2 15.4 17.2 16.7 15.1 13.4 13.7 14.2 14.5 16.7
 14.9 13.6 15.8 16.6 18.2 18.2 15.4 13.2 14.9 15.  14.  14.4 20.1 24.8
 13.2 19.2 16.  12.9 14.7 15.5 16.5 20.1 15.8 17.5 15.2 14.4 21.7 19.9
 13.8 18.  11.4 15.1 17.  16.4 12.6 16.9 16.1 19.4 16.  16.2 14.2 14.4
 14.8 20.4 19.6 13.8 19.  16.6 18.6 16.2 18.  20.5 18.2 

8.Show how to select the number `99` in the array below. 

In [93]:
select_99 = np.array([[1,2,3],
                      [4,5,99]])

select_99[1][2]

99

9.Select the last element in each subarray (do this with one operation.)

In [95]:
select_more = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
# returns array([3, 6, 9])

print("[",select_more[0][2], select_more[1][2], select_more[2][2],"]") 



[ 3 6 9 ]


10.Use the built-in `np.lookfor()` function to search for `'log'`.

Use the function you find and apply it to `mpg`.

In [98]:
np.lookfor('log')

Search results for 'log'
------------------------
numpy.log
    Natural logarithm, element-wise.
numpy.log2
    Base-2 logarithm of `x`.
numpy.log10
    Return the base 10 logarithm of the input array, element-wise.
numpy.log1p
    Return the natural logarithm of one plus the input array, element-wise.
numpy.logspace
    Return numbers spaced evenly on a log scale.
numpy.logaddexp
    Logarithm of the sum of exponentiations of the inputs.
numpy.logaddexp2
    Logarithm of the sum of exponentiations of the inputs in base-2.
numpy.logical_or
    Compute the truth value of x1 OR x2 element-wise.
numpy.logical_and
    Compute the truth value of x1 AND x2 element-wise.
numpy.logical_not
    Compute the truth value of NOT x element-wise.
numpy.logical_xor
    Compute the truth value of x1 XOR x2, element-wise.
numpy.ma.log
    Natural logarithm, element-wise.
numpy.ma.log2
    Base-2 logarithm of `x`.
numpy.ma.log10
    Return the base 10 logarithm of the input array, element-wise.
numpy.rec

In [99]:
np.log10(mpg)

/var/folders/jl/_v7nhy4x6ns_kxmg8nxmzggr0000gn/T/ipykernel_46621/1914124698.py:1: RuntimeWarning: divide by zero encountered in log10
  np.log10(mpg)


array([1.25527251, 1.17609126, 1.25527251, 1.20411998, 1.23044892,
       1.17609126, 1.14612804, 1.14612804, 1.14612804, 1.17609126,
             -inf,       -inf,       -inf,       -inf,       -inf,
       1.17609126, 1.14612804,       -inf, 1.17609126, 1.14612804,
       1.38021124, 1.34242268, 1.25527251, 1.32221929, 1.43136376,
       1.41497335, 1.39794001, 1.38021124, 1.39794001, 1.41497335,
       1.32221929, 1.        , 1.        , 1.04139269, 0.95424251,
       1.43136376, 1.44715803, 1.39794001, 1.39794001,       -inf,
       1.2787536 , 1.20411998, 1.23044892, 1.2787536 , 1.25527251,
       1.14612804, 1.14612804, 1.14612804, 1.14612804, 1.07918125,
       1.11394335, 1.11394335, 1.25527251, 1.34242268, 1.2787536 ,
       1.25527251, 1.36172784, 1.44715803, 1.47712125, 1.47712125,
       1.49136169, 1.54406804, 1.43136376, 1.41497335, 1.38021124,
       1.39794001, 1.36172784, 1.30103   , 1.32221929, 1.11394335,
       1.14612804, 1.17609126, 1.14612804, 1.23044892, 1.04139

11.You your google skills to find the unique items in `origin`. (This may not have been covered in the readings.)

In [26]:
#type(origin)
origin_test = [0,6,5,0,6,5]


array([0, 5, 6])

In [199]:
def unique_items():
    origin_test = [0,6,5,0,6,5]
   
    # empty list created
    new = []
     
    # iterate over all elements to see if they are in the new list
    for x in origin_test:
        if x not in new:
            new.append(x)
    print(new)

unique_items()

[0, 6, 5]


In [201]:
def unique_origins():
    origin = df.Origin.to_numpy()
    org = np.array(origin)
    # empty list created
    unique_org = []
     
    # iterate over all elements to see if they are in the new list
    for x in org:
        if x not in unique_org:
            unique_org.append(x)
    print(unique_org)

unique_origins()
    

['US', 'Europe', 'Japan']


12.
- Create a 2D array and print its shape as well as ndim. (Any shape is fine)

- Create a 3D array and print its shape as well as ndim.

- Create a 4D array and print its shape as well as ndim. *It's hard to visualize 4-Dimensions but numpy can do it with ease!*

In [125]:
#2D Array
a = np.array([[2,4,6],[12,14,16]])
print("2D:",a)
print(a.ndim)
print(a.shape)

#3D Array
b = np.array([[2,4,6],[12,14,16]],ndmin=3)
print("3D:", b)
print(b.ndim)
print(b.shape)
#4D Array

c = np.array([[2,4,6],[12,14,16]],ndmin=4)
print("4D:", c)
print(c.ndim)
print(c.shape)

2D: [[ 2  4  6]
 [12 14 16]]
2
(2, 3)
3D: [[[ 2  4  6]
  [12 14 16]]]
3
(1, 2, 3)
4D: [[[[ 2  4  6]
   [12 14 16]]]]
4
(1, 1, 2, 3)


13.Use boolean indexing to create an array of `True/False` using `origin` and the value 'US'.

In [212]:
org = np.array(origin) #origin array
org == 'US'            #indicates 'true' if values are "US" and false if values do not = 'US'

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True, False, False, False,
       False, False, False,  True,  True,  True,  True,  True, False,
        True, False,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False, False, False, False, False,
        True, False,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True, False, False, False, False,  True, False, False,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True, False,  True,
       False, False,  True,  True, False,  True,  True, False, False,
       False, False,

In [203]:
def US ():
    origin = df.Origin.to_numpy()
    org = np.array(origin)
    empty= []
    for x in org:
        if x == 'US':
            empty.append('True')
        else:
            empty.append('False')
    print(empty)

In [204]:
US ()

['True', 'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True', 'False', 'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True', 'False', 'True', 'True', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'True', 'True', 'True', 'True', 'True', 'False', 'True', 'False', 'True', 'False', 'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True', 'False', 'False', 'False', 'False', 'False', 'False', 'True', 'False', 'True', 'False', 'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True', 'False', 'True', 'True', 'True', 'True', 'False', 'False', 'False', 'False', 'True', 'False', 'False', 'True', 'False', 'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True', 'True', 'False', 'True', 'True', 'True', 'True', 'True', 'False', 'True', 'False', 'False', 'True', 'True', 

14.Apply your index (from above) to the `car` array. You should now only see cars that are of US origin. 

In [213]:
CR[org == 'US']

array(['Chevrolet Chevelle Malibu', 'Buick Skylark 320',
       'Plymouth Satellite', 'AMC Rebel SST', 'Ford Torino',
       'Ford Galaxie 500', 'Chevrolet Impala', 'Plymouth Fury iii',
       'Pontiac Catalina', 'AMC Ambassador DPL',
       'Chevrolet Chevelle Concours (sw)', 'Ford Torino (sw)',
       'Plymouth Satellite (sw)', 'AMC Rebel SST (sw)',
       'Dodge Challenger SE', "Plymouth 'Cuda 340",
       'Ford Mustang Boss 302', 'Chevrolet Monte Carlo',
       'Buick Estate Wagon (sw)', 'Plymouth Duster', 'AMC Hornet',
       'Ford Maverick', 'AMC Gremlin', 'Ford F250', 'Chevy C20',
       'Dodge D200', 'Hi 1200D', 'Chevrolet Vega 2300', 'Ford Pinto',
       'AMC Gremlin', 'Plymouth Satellite Custom',
       'Chevrolet Chevelle Malibu', 'Ford Torino 500', 'AMC Matador',
       'Chevrolet Impala', 'Pontiac Catalina Brougham',
       'Ford Galaxie 500', 'Plymouth Fury iii', 'Dodge Monaco (sw)',
       'Ford Country Squire (sw)', 'Pontiac Safari (sw)',
       'AMC Hornet Sportabout (

array(['Chevrolet Chevelle Malibu', 'Buick Skylark 320',
       'Plymouth Satellite', 'AMC Rebel SST', 'Ford Torino',
       'Ford Galaxie 500', 'Chevrolet Impala', 'Plymouth Fury iii',
       'Pontiac Catalina', 'AMC Ambassador DPL',
       'Chevrolet Chevelle Concours (sw)', 'Ford Torino (sw)',
       'Plymouth Satellite (sw)', 'AMC Rebel SST (sw)',
       'Dodge Challenger SE', "Plymouth 'Cuda 340",
       'Ford Mustang Boss 302', 'Chevrolet Monte Carlo',
       'Buick Estate Wagon (sw)', 'Plymouth Duster', 'AMC Hornet',
       'Ford Maverick', 'AMC Gremlin', 'Ford F250', 'Chevy C20',
       'Dodge D200', 'Hi 1200D', 'Chevrolet Vega 2300', 'Ford Pinto',
       'AMC Gremlin', 'Plymouth Satellite Custom',
       'Chevrolet Chevelle Malibu', 'Ford Torino 500', 'AMC Matador',
       'Chevrolet Impala', 'Pontiac Catalina Brougham',
       'Ford Galaxie 500', 'Plymouth Fury iii', 'Dodge Monaco (sw)',
       'Ford Country Squire (sw)', 'Pontiac Safari (sw)',
       'AMC Hornet Sportabout (

15.Why might you prefer an `np.array()` over a Python `list`? And when is a Python `list` preferred? 

In [ ]:
#You may prefer np.array because it allows you to carry out operations over entire collection of values. 
#It helps with doing calculations over lists instead of individual list elements which would take longer.

#You may prefer a list if you are only working with one set of data elements and the elements are of different
#types. This is because arrays can only contain 1 types of elements within. 

16.What is an identity matrix? 
Create an identiy matrix of size 5 using an np method. 

In [171]:
#The identity array or matrix is a square array (3 elements by 3 elements for example) 
#with ones on the main diagonal.

IM = np.identity(5)
IM

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

17.Transpose the following array. 

In [173]:
transpose_me = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])


In [174]:
np.transpose(transpose_me)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

**The remaining questions are OPTIONAL**: The readings did not address all of these so you may have to use some "Google-Fu". 

1.Why does this multiplication operation fail? 

In [ ]:
arr1 = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
arr2 = np.array([[1,2,3],
                      [4,5,6]])

arr1 * arr2

Use numpy to answer the following questions. 

2.What is the average horsepower for `Europe` cars? (Hint: create boolean index of 'US' apply it to horsepower and perform the calculation.)

3.On average are Japanse cars more fuel efficient than US cars? 

4.What is the correlation coefficient of `mpg` and `weight`? What is a correlaton coefficient?