In [4]:
class Music:
    @staticmethod #static method cant access class or obj state so
                  #we do not need to call on the 'self' or obj
    def play(): 
        print("*playing music*")
        
    def stop(self): #this is not a static method, therefore it
                    #can access/modify class and obj. 
                    #Self implies that the method is related to an 
                    #instance of the class
        print("stop playing")

In [5]:
Music.play() #class.method()

*playing music*


In [6]:
Music.stop() #this does not work becuz the method stop(), has 'self'
             #as an argument, which means that the method is 
             #refering to an instance of class. So we need to create 
             #an instance.

TypeError: stop() missing 1 required positional argument: 'self'

In [7]:
song = Music() #an instance of class Music() is created
song.stop()

stop playing


In [8]:
class AllTheClassMethods:
    def method(self):
        return 'instance method called', self
    
    @classmethod
    def classmethod (cls):
    #cls: implies that the method belongs to the class.
    #cls(class) is automaticlly passed as the 
    #1st argument of a class method
        return 'class method called', cls
    
    @staticmethod
    def staticmethod():
        return 'static method called' #not going to call anything
                                      #becuz it is not accepting 
                                      #an obj in the ()

In [9]:
#calling classmethod()...
AllTheClassMethods.classmethod() 

#main is called name space-->Used when working w/ complicated info.
#and symbolizes the names assigned to the obj.

('class method called', __main__.AllTheClassMethods)

In [10]:
#calling staticmethod..
AllTheClassMethods.staticmethod() 

#didn't give us much info. becuz static method does only basic logic

'static method called'

In [11]:
AllTheClassMethods.method()
#we need to create an obj to call to avoid the error below

TypeError: method() missing 1 required positional argument: 'self'

In [12]:
obj=AllTheClassMethods()
obj.method()

#outputting location in memory 

('instance method called', <__main__.AllTheClassMethods at 0x7fb923caf250>)

In [ ]:
#NUMPY: all about arrays, its a library, does fundamental operations
#array-->all the elements are the same type, you can do something to
    #all of them because of that. Consume less memory
#Arrays-->structered lists of #s
    #EX: Vectors, matrices, images, tensors, ConvNets
    #Vectors- direction and magnitude two dimensonal array
    #matrix-multiple dimentions
    #Tensors-obj that descrive reltionship between sets of obj, 
    #multidimensional array (more than 3 dimensions)
    #ConvNets- images changing.
#1-Arrays can have any # of dimensions, including 0 (a scalar).
#2- Arrays are typed: np.uint8, np.int64, np.float32, np.float64
    #uint--only positive #s, takes less memory
#3- Arrays are dense. Each element of the array exists & has
    #the same type 
#4- Arrays are faster than python lists (consume less memory)

In [48]:
#always import at the top of your code
import numpy as np
a = np.array([[1,2,3],[4,5,6]], dtype=np.float32)
a

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [18]:
print(a.ndim, a.shape, a.dtype)

#ndim--# of dimensions
#shape-gives all the dimensions (2 by 3) 
#dtype--type (float) 
#takes up 32 bytes of memory

2 (2, 3) float32


In [25]:
import numpy as np
b = np.array([[[2,4,6],[8,10,12]]], dtype=np.float32)
b

array([[[ 2.,  4.,  6.],
        [ 8., 10., 12.]]], dtype=float32)

In [26]:
print(b.ndim, b.shape, b.dtype)

3 (1, 2, 3) float32


In [28]:
c = np.array([[[2,4,6],[8,10,12]]],ndmin=6)

In [29]:
c

array([[[[[[ 2,  4,  6],
           [ 8, 10, 12]]]]]])

In [31]:
c.ndim

6

In [40]:
d = np.ones((3,2))
d

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [41]:
d.ndim

2

In [42]:
d.shape

(3, 2)

In [49]:
import pandas as pd
import numpy as np

# Read in dataset
df = pd.read_csv('cars.csv',delimiter=';')

# Convert each column to an np.array
car = df.Car.to_numpy()
CR = np.array(car)
print(CR)

mpg = df.MPG.to_numpy()
empg = np.array(mpg)
print(empg) 

cylinders = df.Cylinders.to_numpy()
clnder = np.array(cylinders)
print(clnder)

displacement = df.Displacement.to_numpy()
displace = np.array(displacement)
print(displace)

horsepower = df.Horsepower.to_numpy()
HP = np.array(horsepower)
print(HP)

weight = df.Weight.to_numpy()
weyt = np.array(weight)
print(weyt)

acceleration = df.Acceleration.to_numpy()
acc = np.array(acceleration)
print(acc)

model = df.Model.to_numpy()
mdl = np.array(model)
print(mdl)

origin = df.Origin.to_numpy()
org = np.array(orgin)
print(org)

# create an array of headers
headers = np.array(['Car', 'MPG', 'Cylinders', 'Displacement', 'Horsepower', 'Weight','Acceleration', 'Model', 'Origin'])
print(headers)

FileNotFoundError: [Errno 2] No such file or directory: 'cars.csv'

In [ ]:
X = np.array(df.iloc[0:406, 0:9])
print(headers)
print(X)